services:
  web:
    image: ghcr.io/stardogg/docker-php-5.2
    ports:
      - published: 8000
        target: 80
        protocol: 'tcp'
        mode: 'host'
    volumes:
      - .:/var/www/html
    environment:
      TZ: 'America/Chicago'
      XDEBUG_REMOTE_ENABLE: 1
      XDEBUG_REMOTE_HOST: host.docker.internal
      XDEBUG_REMOTE_PORT: 9000
      PHP_DISPLAY_ERRORS: 'on'
      PHP_HTML_ERRORS: 'on'
      PHP_LOG_ERRORS: 'on'
    networks:
      - 'mysql'

  mysql:
    image: docker.io/mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "010203"
      MARIADB_DATABASE: "test"
      MARIADB_USER: "php"
      MARIADB_PASSWORD: "010203"
    networks:
      - 'mysql'

networks:
  mysql:
    external: true
    name: 'mysql'
