ServerName localhost
AddType application/x-httpd-php .php .phtml
User www-data
Group www-data

CustomLog "/var/log/apache/access_log" common
ErrorLog "/var/log/apache/error_log"

DirectoryIndex index.html index.php

DocumentRoot "/var/www/html"
<Directory "/var/www/html">
    Options Indexes FollowSymLinks
    AllowOverride All
    Allow from all
</Directory>
